### ISSUE TITLE
Multiple uses resets pop up

### ISSUE THREAD

**Issue by dewray** [ndunand/moodle-atto_corrections#1]
Using Moodle 3.5, the pop-up reflects the menu choices for the first student, but thereafter open with the top item selected, regardless of which option is chosen. This means I must select an annotation two times.

**Comment by ndunand** [comment]
Sorry I can't really understand the problem. Could you please explain the exact steps you're taking and where the outcome is not what you expect?

**Comment by dewray** [comment]
I beg your pardon.
These are the steps I take:
1. I open the assignment grade function using Moodle 3.5.
2. I grade an assignment. The plugin functions as it should: if I choose the third item from the atto toolbar menu, a popup for the third item appears, and I can make appropriate comments and save the correction.
3. I save the grade and go the next homework.
4. I choose a correction item from the atto toolbar. However, if I choose the third item (or any other item), only the popup for the first item appears. This happens each time I choose any item from the atto toolbar and always happens after I save the first assignment.
5. The problem disappears if I refresh the page, but reappears just after I have saved.

I am using Maria db with nginx on an Ubuntu server; also, I have modified the texts in the correction items so that both English and Japanese are written in them.

**Comment by ndunand** [comment]
Thanks for taking the time to describe in more detail. Indeed this is not as designed. I'll try to fix this in the next release.

**Comment by vfonsecaz** [comment]
Yes I can confirm this behaviour in moodle 3.5.
I saw the source code with some "todo" comments :)
Maybe I'll try to fix this on my own.

**Comment by ndunand** [comment]
@vfonsecaz Thanks for confirming this; as I have little time to work on non-blocking issues, any help would be welcome and quickly reviewed.

**Comment by vfonsecaz** [comment]
After inspecting the page i realized each time you make "_save_" the "_atto_form_" element remains in the page. When trying to add a new correction another "atto_form" element is created by the `__getDialogueContent_` call , so the `_Y.one('.atto_form...._ ` selector becomes invalid has you have more than one atto_form element

I'm not familiar with the YUI framework. My workaround was checking for an existing _atto_form_ element in the page before creating a new one. If one exists, then remove it from the page.

**moodle-atto_corrections-button.js**

```
_displayDialogue: function(args, selectednode) {
...
		//remove previous atto_form elemen before creating a new one (_getDialogueContent)		
		if (Y.one('.atto_form'))
			Y.one('.atto_form').remove();			

        // Set the dialogue content, and then show the dialogue.
        dialogue.set('bodyContent', this._getDialogueContent())
                .show();
...
```

**Comment by ndunand** [comment]
Ok, we'll be looking into this. Just adding a screen recording so I can remember how to test.

![ezgif-2-e1ad68070fc1](https://user-images.githubusercontent.com/762972/86354798-f8cd1800-bc69-11ea-8573-e78cb158255c.gif)

**Comment by dewray** [comment]
The problem I reported for Moodle 3.5 persists in Moodle 3.9.1 (Build: 20200713).

**Comment by NicoAlexH** [comment]
Hello @dewray, @vfonsecaz 
this issue has been resolved in the last release. Thank you for your help !
