### ISSUE TITLE
Correction text popup window - no scroll

### ISSUE THREAD

**Issue by vfonsecaz** [ndunand/moodle-atto_corrections#2]
When clicking the button "Display text with correction marks" the popup won't show the full correction text when it is too big (no scrollbar)

I changed my theme's custom.css file
`.atto_corrections_fulltext {
    height:  600px;
    overflow-y:  auto;
}`

**Comment by ndunand** [comment]
Hello, this seems to be related to your theme. Which theme are you using ?

**Comment by vfonsecaz** [comment]
hi,

it's adaptable (v2.2.2)

**edit**: just checked and it seems and update to the theme has solved the problem!

thanks

**Comment by ndunand** [comment]
ok thanks for reporting back
