### ISSUE TITLE
Feature idea: Only available to users with specific capability

### ISSUE THREAD

**Issue by marcusgreen** [ndunand/moodle-atto_corrections#3]
Would you be interested in some code that ensured that the button would only appear for users with the capability 
course:manageactivities (i.e. teachers and similar)

e.g. in the method in lib.php
atto_corrections_params_for_js($elementid, $options, $fpoptions) {

You do 
    global $COURSE;
    $coursecontext = context_course::instance($COURSE->id);
    $disabled = false;
    if (!has_capability('moodle/course:manageactivities', $coursecontext)) {
        $disabled = true;
    }
And then in your 
button.js
   initializer: function() {

You do 
        // If we don't have the capability to view then give up.
        if (this.get('disabled')) {
            return;
        }

What do you think?

**Comment by ndunand** [comment]
Hi Marcus,

Thanks for the idea, this is interesting. However this may be too constricted for some of my use cases. What about creating a specific capability instead? I'm thinking something like `atto/corrections:canmarkup`, and then check for this capability.

**Comment by marcusgreen** [comment]
That is a much better idea,  I will create a branch on my fork and have a play with it. What are your main use cases?

**Comment by ndunand** [comment]
No real use case yet, but I'm always for more flexibility.

Off the top of my head, I could think of a collaborative wiki where only the teacher would be able to use the atto_corrections tool. Then possibly one could use overrides to come up with various other scenarii.

What would be yours?

**Comment by marcusgreen** [comment]
I have something working in the branch capabilities.
https://github.com/marcusgreen/moodle-atto_corrections/tree/capabilities
You might want to comment on what I have done in this file
https://github.com/marcusgreen/moodle-atto_corrections/blob/capabilities/db/access.php

**Comment by ndunand** [comment]
Thanks! I just had a look and posted some minor comments.

**Comment by marcusgreen** [comment]
Excellent, I will explore all of your suggestions.

**Comment by ndunand** [comment]
@NicoAlexH could you have a look at this?

**Comment by NicoAlexH** [comment]
Hello @marcusgreen, 
I have merged your work with some modifications in order to stick to Moodle conventions. This feature is now available in the new release. Thanks for your help !

**Comment by marcusgreen** [comment]
Wonderful!
