### ISSUE TITLE
Button icons not rendered in atto toolbar

### ISSUE THREAD

**Issue by dewray** [ndunand/moodle-atto_corrections#4]
When corrections is added to a toolbar in 3.10.1+ (Build: 20210219) (or any previous builds from about 3.8), the button icons do not render,
The problem continues when

- using Boost theme
- using Fordson theme
- when icons are converted to svg
- when corrections plugin is freshly installed or uninstalled and reinstalled
- when "corr = corrections" is placed last or not placed last in the toolbar

![correctionstoolbar](https://user-images.githubusercontent.com/35580043/108562271-f7f50d80-7342-11eb-82e9-72d884e543f1.jpg)

Ubuntu 18.04
Mariadb 10.3.27
php 7.2.24 with all recommended extensions

**Comment by dewray** [comment]
Using the Chrome developer tools, the error I get is "Failed to load resource: the server responded with a status of 404 ()." Same problem when using Firefox. Same problem using Fordson theme and Boost theme.

**Comment by nuria2c** [comment]
Hi,
We have the same problem. It seems that the URL image generated during the render is incorrect.
The URL duplicates is the path real path duplicated:
https://site.com/theme/image.php/site/core/1620985639/https://site.com/theme/image.php/site/atto_corrections/1620985639/icon2
If you modify this URL in the debug panel, the images appear correctly.

**Comment by ndunand** [comment]
Hi, did you paste this directly ? Your url contains another error which could be a lead to a fix:

`https:/site.com` should have a double slash, not single. Is that an editing error or the actual result?

**Comment by nuria2c** [comment]
No, I've changed the URL manually to anonymize the information. I've changed it now.

**Comment by ndunand** [comment]
Can we confirm you're using the latest version of the plugin? I've just tested in 3.11 and the buttons display as expected.

> 1.0.7 for Moodle 2.7-3.5 (Build 2018050201)

**Comment by nuria2c** [comment]
We are  using:
- Moodle version 3.10.1+ (Build: 20210122) Boost theme
- Plugin version 1.0.7 for Moodle 2.7-3.5 (Build 2018050201) 2018050201

It seems is the last one....

**Comment by dewray** [comment]
The buttons on my system are now rendering correctly. I am afraid I do not know when they started doing so, but it was after a moved to a new server (with Ubuntu 20.04 and all latest requisite software). Presently I'm using Moodle 3.11, but it worked with several flavors of 3.10 also.

**Comment by ndunand** [comment]
Thanks for reporting back. Alright, so the issue likely lies elsewhere in the software stack. I'm closing this for now but feel free to reopen if needed.
