### ISSUE TITLE
button icons not rendered in atto toolbar

### ISSUE THREAD

**Issue by a-marti** [ndunand/moodle-atto_corrections#5]
I found the bug related to issue #4, now closed.

The issue still happening using nginx.

After checking your plugin code, I found that you are using M.util.image_url for icon image when use addButton function from atto editor source. The function addButton, use M.util again and this causes wrong url:
https://mysite.com/theme/image.php/boost/core/1637325913/https://mysite.com/theme/image.php/boost/atto_corrections/1637325913/icon1

Working one is:
https://mysite.com/theme/image.php/boost/atto_multilang2/1637325913/icon

So I've tried to adapt button.js from your plugin, like other plugins do and now is working.

Old button.js code:
![Captura de pantalla de 2021-11-30 13-59-09](https://user-images.githubusercontent.com/36474613/144052683-28f3b37e-d6b6-48fe-83e7-dda3a44701d6.png)

New button.js code
![Captura de pantalla de 2021-11-30 14-00-15](https://user-images.githubusercontent.com/36474613/144052705-e9ad93f0-dbe4-44dc-91ae-57e0d1e0c20f.png)
:

**Comment by a-marti** [comment]
I proposed a pull request #6

**Comment by ndunand** [comment]
Fixed by #6 . Thanks @a-marti for finding the underlying issue!
